CREATE TABLE notifications (
	id VARCHAR(26) PRIMARY KEY,
  doctor_id VARCHAR(36) NULL REFERENCES doctors(id) ON DELETE CASCADE,
	hospital_id INT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  body TEXT NULL,
  type INT NOT NULL DEFAULT(1),
  read_at TIMESTAMP NULL,
	metadata JSONB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
